### PR TITLE
enable to use y and n instead of yes and no

### LINKED ISSUE #2: Make the program take input y/n instead of yes/no
The program currently takes an input of yes/no while asking the user to share the program with friends. Change it so that the program takes the input y/n making the program easy to use. This is a very beginner-friendly problem and requires very less knowledge of programming but still if you have any queries ask me in the comment.

**Make sure to get assigned before starting to work on the issue.**

### PR DESCRIPTION
**Pull request by cpyberry**
Hello, I am cpyberry.
If you happen to have a free moment, I'd be very glad if you could give me your opinion.

## Contents

* I prepared a list representing yes and a list representing no and combined them
* judgment of choice is done in the function
* more description

## Reasons

* By preparing a list representing yes and a list representing no separately, the amount of writing literals has been reduced, making it easier to handle even if there are more options for yes and no in the future.

## Issue

fixed #2

### CODE REVIEW

**Comment by cpyberry** [comment]
@itsabhianant

sorry I have failed
I misunderstood that I would assign it to an issue
Should I close the pull request?

**Comment by noturshek** [comment]
> @itsabhianant
> 
> sorry I have failed
> I misunderstood that I would assign it to an issue
> Should I close the pull request?

Actually, you have to remove the program's ability to take the yes/no input and program it to take values y/n instead of yes/no. You can either try editing it by one more commit or you can delete this PR and create a new one making suitable changes

**Comment by cpyberry** [comment]
Only y and n remained in the choices

**Comment by noturshek** [comment]
> Only y and n remained in the choices

Can you please add Fixes #2  in you top comment so that the issue gets closed as soon as I merge it with my master branch

**Comment by noturshek** [comment]
> Hello, I am cpyberry.
> If you happen to have a free moment, I'd be very glad if you could give me your opinion.
> 
> ## Contents
> * I prepared a list representing yes and a list representing no and combined them
> * judgment of choice is done in the function
> * more description
> 
> ## Reasons
> * By preparing a list representing yes and a list representing no separately, the amount of writing literals has been reduced, making it easier to handle even if there are more options for yes and no in the future.
> 
> ## Issue
> #2

Add Fixes #2 in these comment.

**Comment by cpyberry** [comment]
I wrote "fixed"
Now when this pull request is merged, the issue will be closed

**Comment by cpyberry** [comment]
Thank you for merging
I'm probably your cup of coffee XD

**Comment by noturshek** [comment]
LOL XD

**Pull request merged**
